### ISSUE TITLE
Why 2 satoshi for candidate?

### ISSUE THREAD

**Issue by aemxn** [arikan/bitcoin-voting#1]
Interesting implementation. I would like to enquire regarding the candidate registration at the 3rd schema. Can you clarify why those candidates are given 2 satoshi for their registration?

Also, how do you think rigging can be eliminated from this implementation? For instance, 10 voters created 100 different bitcoin addresses on their own, for voting purpose.

Thanks

**Comment by arikan** [comment]
Hi @aimanbaharum, thanks for the questions.

The idea of sending 2 Satoshi to candidates and 1 Satoshi to the voters is just to differentiate those two types of actors. So that in the blockchain, these transactions can be easily identifiable. 

```
Election Authority -2 Satoshi-> Candidate
Election Authority -1 Satoshi-> Voter
```

Rigging is eliminated through an old schema: in order to get registered for the election, each Voter must declare a valid ID to the Election Authority.

>  Voters show a valid ID and provide their Bitcoin address to Election Authority, who sends them 0.00000001 BTC in return.

**Comment by arikan** [comment]
@aimanbaharum also see the update with time limited election on schema section 5 https://github.com/arikan/bitcoin-voting/commit/721f447e2680431754e7a5d324aacc2af5c8e6c7

**Comment by aemxn** [comment]
Cool, thanks for the explanation.

I'm pulling a new request now.
